ce100_hw2_haluk_kurtulus.GFG3 Class Reference
Static Public Member Functions
static int MatrixChainOrder (int[] p, int n)
Static Public Attributes
static int[,] dp = new int[100, 100]
Static Private Member Functions
static int matrixChainMemoised (int[] p, int i, int j)
Member Function Documentation
matrixChainMemoised()
static int ce100_hw2_haluk_kurtulus.GFG3.matrixChainMemoised (int[] p, int i, int j) [inline], [static], [private]
References ce100_hw2_haluk_kurtulus.GFG3.dp, and ce100_hw2_haluk_kurtulus.GFG3.matrixChainMemoised().
Referenced by ce100_hw2_haluk_kurtulus.GFG3.matrixChainMemoised(), and ce100_hw2_haluk_kurtulus.GFG3.MatrixChainOrder().
MatrixChainOrder()
static int ce100_hw2_haluk_kurtulus.GFG3.MatrixChainOrder (int[] p, int n) [inline], [static]
References ce100_hw2_haluk_kurtulus.GFG3.matrixChainMemoised().
Referenced by ce100_hw2_test.HeapSortTest.MatrixChainOrder_BestCase_ReturnsCorrectResult(), MatrixChainMultiplicationTests.TestMatrixChainMultiplication(), ce100_hw2_test.HeapSortTest.TestMatrixChainOrder_AverageCase(), and ce100_hw2_test.HeapSortTest.TestWorstCasegfc3().
Field Documentation
dp
int [,] ce100_hw2_haluk_kurtulus.GFG3.dp = new int[100, 100] [static]
Referenced by ce100_hw2_haluk_kurtulus.GFG3.matrixChainMemoised().
The documentation for this class was generated from the following file:
C:/ce100-hw2-haluk-kurtulus/ce100-hw1-haluk-kurtulus/Class1.cs